Update tee.yml

diff --git a/.github/workflows/tee.yml b/.github/workflows/tee.yml
--- a/.github/workflows/tee.yml
+++ b/.github/workflows/tee.yml
@@ -1,18 +1,15 @@
-name: tee-odd
+name: sgx-build-azure-ssh
 
 on:
   push:
-    branches: [ "quote-presentation-cix" ]
+    branches: [ "quote-presentation-ci" ]
   pull_request:
-    branches: [ "quote-presentation-cix" ]
-
+    branches: [ "quote-presentation-ci" ]
+    
+# perms needed for attestation workflow
 permissions:
   id-token: write
   attestations: write
-  
-env:
-  CARGO_TERM_COLOR: always
-  SGX: 1
 
 jobs:
   build:
@@ -22,8 +19,8 @@ jobs:
     - name: azure-tee-build-${{ github.sha }}
       uses: appleboy/ssh-action@v1.0.3
       env:
+         # using personal access token until devops links acct
          PAT_TOKEN: ${{ secrets.PAT_SET_ENV }}
-
       with:
          host: ${{ secrets.AZURE_TEE_BUILD_HOST }}
          username: ${{ secrets.AZURE_TEE_BUILD_USERNAME }}
@@ -42,16 +39,15 @@ jobs:
             cd crates/notary/server/config/gramine
             random_port=$(shuf -i 1024-65535 -n 1)
             sed -i '/port*: *7047/s/7047/'$random_port'/' ../config.yaml
-            SGX=1 make clean
-            SGX=1 make
-            SGX=1 make start-gramine-server
+            make clean
+            SGX=1 make start-gramine-server &
             notarypid=$!
-            BINGO=0
-            SECONDS=0; set -o pipefail; while [ $SECONDS -lt 300 ]; do echo -e "GET /info HTTP/1.1\r\nHost: localhost\r\nConnection: Close\r\n\r\n" |  openssl s_client -quiet -ignore_unexpected_eof localhost:$random_port 2>&1| tee s.log;  if [ $? -eq 0 ]; then BINGO=1; break; fi;  sleep 2; done
-            kill $notarypid
-            if [ "$BINGO" -eq 0 ]; then exit 1; fi
+            win=0
+            SECONDS=0; set -o pipefail; while [ $SECONDS -lt 300 ]; do echo -e "GET /info HTTP/1.1\r\nHost: localhost\r\nConnection: Close\r\n\r\n" | openssl s_client -quiet localhost:$random_port 2>&1 | tee s.log; if [ $? -eq 0 ]; then win=1; break; fi; sleep 2; done
+            if [ $win -eq 0 ]; then echo "Build Failed"; kill -SIGTERM $notarypid; exit 1; fi
             export RAWQUOTE=$(cat s.log | grep '^{' |  jq '. | tostring')
             curl -L -X PATCH -H "Accept: application/vnd.github+json" -H "Authorization: Bearer $PAT_TOKEN" -H "Connection: close" -H "X-GitHub-Api-Version: 2022-11-28" https://api.github.com/repos/$GITHUB_REPOSITORY/environments/TEE/variables/AZURE_TEE_BUILD_PORT -d "{\"name\":\"AZURE_TEE_BUILD_PORT\",\"value\":$RAWQUOTE}"
+            kill -SIGTERM $notarypid
             exit 0
     - name: save quote from azure into env, write it to runner
       run: echo "${{ vars.AZURE_TEE_BUILD_PORT }}" > /home/runner/work/_temp/sgx-build-quote.txt
@@ -63,5 +59,3 @@ jobs:
       uses: actions/attest-build-provenance@v1
       with:
         subject-path: /home/runner/work/_temp/sgx-build-quote.txt
-
- 
