Update test.yml

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -43,9 +43,10 @@ jobs:
             notarypid=$!
             BINGO=0
             SECONDS=0; set -o pipefail; while [ $SECONDS -lt 19 ]; do echo -e "GET /info HTTP/1.1\r\nHost: localhost\r\nConnection: Close\r\n\r\n" | openssl s_client -quiet localhost:$random_port 2>&1 | tee s.log; if [ $? -eq 0 ]; then echo 'BBB'; BINGO=1; break; fi; sleep 2; done
-            if [ $BINGO -eq 0 ]; then echo "Test Failed"; exit 1; fi
+            if [ $BINGO -eq 0 ]; then echo "Test Failed"; kill -SIGTERM notarypid; exit 1; fi
             export RAWQUOTE=$(cat s.log | grep '^{' |  jq '. | tostring')
             curl -L -X PATCH -H "Accept: application/vnd.github+json" -H "Authorization: Bearer $PAT_TOKEN" -H "Connection: close" -H "X-GitHub-Api-Version: 2022-11-28" https://api.github.com/repos/$GITHUB_REPOSITORY/environments/TEE/variables/AZURE_TEE_BUILD_PORT -d "{\"name\":\"AZURE_TEE_BUILD_PORT\",\"value\":$RAWQUOTE}"
+            kill -SIGTERM notarypid
             exit 0
     - name: save quote from azure into env, write it to runner
       run: echo "${{ vars.AZURE_TEE_BUILD_PORT }}" > /home/runner/work/_temp/sgx-build-quote.txt
